# Generated by Django 2.0.3 on 2018-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
