# Generated by Django 2.0.3 on 2018-07-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscribe',
            new_name='email',
        ),
    ]
