# Generated by Django 2.0.3 on 2018-07-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180724_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
