# Generated by Django 2.0.3 on 2018-05-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180502_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculture',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='networking',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='networking',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='politics',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='politics',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='programming',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programming',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='imagesub',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='imagesub',
            field=models.URLField(null=True),
        ),
    ]
