# Generated by Django 2.0.3 on 2018-05-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='health',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='networking',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='politics',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='programming',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='software',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sport',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
