# Generated by Django 2.0.3 on 2018-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180504_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='business',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='health',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='networking',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='politics',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='programming',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='software',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sport',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
