# Generated by Django 2.0.3 on 2018-08-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180712_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hardware',
            new_name='Blog',
        ),
        migrations.DeleteModel(
            name='Agriculture',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.DeleteModel(
            name='lifestyle',
        ),
        migrations.DeleteModel(
            name='Networking',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.DeleteModel(
            name='Politics',
        ),
        migrations.DeleteModel(
            name='Programming',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
